version: '2'

services:
  tls1.2:
    image: nginx
    volumes:
      - ./nginx-tls1.2.conf:/etc/nginx/nginx.conf
      - ./tls1.2.html:/var/www/index.html
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "444:444"
    dns_search:
      - "cute.systems"
    
  tls1.1:
    image: nginx
    volumes:
      - ./nginx-tls1.1-1.2.conf:/etc/nginx/nginx.conf
      - ./tls1.1-1.2.html:/var/www/index.html
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "445:445"
    dns_search:
      - "cute.systems"
    
  tls1.0:
    image: nginx
    volumes:
      - ./nginx-tls1.0-1.2.conf:/etc/nginx/nginx.conf
      - ./tls1.0-1.2.html:/var/www/index.html
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "446:446"
    dns_search:
      - "cute.systems"
